version: "3.8"

services:
  db:
    image: postgres:17.0
    container_name: reminder_db
    environment:
      POSTGRES_DB: reminder
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: