spring:
  application:
    name: reminder
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/reminder
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
  liquibase:
    contexts: prod
